services:
  logbook:
    build: .
    image: logbook:latest
    container_name: logbook
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      NODE_ENV: production
      HOST: 0.0.0.0
      PORT: 3000
    restart: unless-stopped
    volumes:
      - logbook_sqlite:/app/prisma
    networks:
      - proxy

volumes:
  logbook_sqlite:

networks:
  proxy:
    external: true
